-- STORE --

ALTER TABLE INVENTORY
ADD CONSTRAINT FK_STORE_INVENTORY
FOREIGN KEY (STORE)
REFERENCES DISTRIBUTIONCHANNEL(SITE_STORE);

ALTER TABLE SALE
ADD CONSTRAINT FK_STORE_SALE
FOREIGN KEY (STORE)
REFERENCES DISTRIBUTIONCHANNEL(SITE_STORE);

-- PRODUCT --
ALTER TABLE INVENTORY
ADD CONSTRAINT FK_PRODUCT_INVENTORY
FOREIGN KEY (PRODUCT_ID)
REFERENCES PRODUCT(PRODUCT_ID);

ALTER TABLE SALE
ADD CONSTRAINT FK_PRODUCT_SALE
FOREIGN KEY (PRODUCT_ID)
REFERENCES PRODUCT(PRODUCT_ID);