Ndp Phuong
commit;
-- CAP QUYEN CHI NHANH1201
CREATE USER c##CN01 IDENTIFIED BY CN01;
GRANT CONNECT, DBA TO c##CN01;
CREATE USER c##GIAMDOC1 IDENTIFIED BY GIAMDOC1;
CREATE USER c##QUANLYKHO1 IDENTIFIED BY QUANLYKHO1;
CREATE USER c##NHANVIEN1 IDENTIFIED BY NHANVIEN1;


GRANT CREATE PUBLIC DATABASE LINK TO c##CN01;
GRANT CONNECT, DBA TO c##GIAMDOC1;
GRANT CREATE PUBLIC DATABASE LINK TO c##GIAMDOC1;

-- CAP QUYEN CHI NHANH1202
CREATE USER c##CN02 IDENTIFIED BY CN02;
GRANT CONNECT, DBA TO c##CN02;
CREATE USER c##GIAMDOC2 IDENTIFIED BY GIAMDOC2;
CREATE USER c##QUANLYKHO2 IDENTIFIED BY QUANLYKHO2;
CREATE USER c##NHANVIEN2 IDENTIFIED BY NHANVIEN2;

GRANT CREATE PUBLIC DATABASE LINK TO c##CN02;
GRANT CONNECT, DBA TO c##GIAMDOC2;
GRANT CREATE PUBLIC DATABASE LINK TO c##GIAMDOC2;


-- CAP QUYEN CHI NHANH1203
CREATE USER c##CN03 IDENTIFIED BY CN03;
GRANT CONNECT, DBA TO c##CN03;
CREATE USER c##GIAMDOC3 IDENTIFIED BY GIAMDOC3;
CREATE USER c##QUANLYKHO3 IDENTIFIED BY QUANLYKHO3;
CREATE USER c##NHANVIEN3 IDENTIFIED BY NHANVIEN3;


GRANT CREATE PUBLIC DATABASE LINK TO c##CN03;
GRANT CONNECT, DBA TO c##GIAMDOC3;
GRANT CREATE PUBLIC DATABASE LINK TO c##GIAMDOC3;

-- CAP QUYEN CHI NHANH1204
CREATE USER c##CN04 IDENTIFIED BY CN04;
GRANT CONNECT, DBA TO c##CN04;
CREATE USER c##GIAMDOC4 IDENTIFIED BY GIAMDOC4;
CREATE USER c##QUANLYKHO4 IDENTIFIED BY QUANLYKHO4;
CREATE USER c##NHANVIEN4 IDENTIFIED BY NHANVIEN4;


GRANT CREATE PUBLIC DATABASE LINK TO c##CN04;
GRANT CONNECT, DBA TO c##GIAMDOC4;
GRANT CREATE PUBLIC DATABASE LINK TO c##GIAMDOC4;



GRANT CREATE SESSION, DBA TO c##GIAMDOC1;
GRANT CREATE SESSION, DBA TO c##GIAMDOC2;
GRANT CREATE SESSION, DBA TO c##GIAMDOC3;

-- cn01 --



Create table c##CN01.DISTRIBUTIONCHANNEL AS  Select * from c##ndp.DISTRIBUTIONCHANNEL;
Create table c##CN01.PRODUCT             AS  Select * from c##ndp.PRODUCT;
Create table c##CN01.INVENTORY           AS  Select * from c##ndp.INVENTORY    where STORE = "1201";
Create table c##CN01.SALE                AS  Select * from c##ndp.SALE         where STORE = "1201";
GRANT SELECT ON c##CN01.DISTRIBUTIONCHANNEL TO c##GIAMDOC1;
GRANT SELECT ON c##CN01.PRODUCT             TO c##GIAMDOC1;
GRANT SELECT ON c##CN01.INVENTORY           TO c##GIAMDOC1;
GRANT SELECT ON c##CN01.SALE                TO c##GIAMDOC1;
GRANT SELECT ON c##CN01.PRODUCT             TO c##QUANLYKHO1;
GRANT SELECT ON c##CN01.INVENTORY           TO c##QUANLYKHO1;
GRANT SELECT ON c##CN01.PRODUCT             TO c##NHANVIEN1;
GRANT SELECT ON c##CN01.SALE                TO c##NHANVIEN1;


Create table c##CN02.DISTRIBUTIONCHANNEL AS  Select * from c##ndp.DISTRIBUTIONCHANNEL;
Create table c##CN02.PRODUCT             AS  Select * from c##ndp.PRODUCT;
Create table c##CN02.INVENTORY           AS  Select * from c##ndp.INVENTORY    where STORE = "1202";
Create table c##CN02.SALE                AS  Select * from c##ndp.SALE         where STORE = "1202";
GRANT SELECT ON c##CN02.DISTRIBUTIONCHANNEL TO c##GIAMDOC2;
GRANT SELECT ON c##CN02.PRODUCT             TO c##GIAMDOC2;
GRANT SELECT ON c##CN02.INVENTORY           TO c##GIAMDOC2;
GRANT SELECT ON c##CN02.SALE                TO c##GIAMDOC2;
GRANT SELECT ON c##CN02.PRODUCT             TO c##QUANLYKHO2;
GRANT SELECT ON c##CN02.INVENTORY           TO c##QUANLYKHO2;
GRANT SELECT ON c##CN02.PRODUCT             TO c##NHANVIEN2;
GRANT SELECT ON c##CN02.SALE                TO c##NHANVIEN2;


Create table c##CN03.DISTRIBUTIONCHANNEL AS  Select * from c##ndp.DISTRIBUTIONCHANNEL;
Create table c##CN03.PRODUCT             AS  Select * from c##ndp.PRODUCT;
Create table c##CN03.INVENTORY           AS  Select * from c##ndp.INVENTORY    where STORE = "1203";
Create table c##CN03.SALE                AS  Select * from c##ndp.SALE         where STORE = "1203";
GRANT SELECT ON c##CN03.DISTRIBUTIONCHANNEL TO c##GIAMDOC3;
GRANT SELECT ON c##CN03.PRODUCT             TO c##GIAMDOC3;
GRANT SELECT ON c##CN03.INVENTORY           TO c##GIAMDOC3;
GRANT SELECT ON c##CN03.SALE                TO c##GIAMDOC3;
GRANT SELECT ON c##CN03.PRODUCT             TO c##QUANLYKHO3;
GRANT SELECT ON c##CN03.INVENTORY           TO c##QUANLYKHO3;
GRANT SELECT ON c##CN03.PRODUCT             TO c##NHANVIEN3;
GRANT SELECT ON c##CN03.SALE                TO c##NHANVIEN3;


Create table c##CN04.DISTRIBUTIONCHANNEL AS  Select * from c##ndp.DISTRIBUTIONCHANNEL;
Create table c##CN04.PRODUCT             AS  Select * from c##ndp.PRODUCT;
Create table c##CN04.INVENTORY           AS  Select * from c##ndp.INVENTORY    where STORE = "1204";
Create table c##CN04.SALE                AS  Select * from c##ndp.SALE         where STORE = "1204";
GRANT SELECT ON c##CN04.DISTRIBUTIONCHANNEL TO c##GIAMDOC4;
GRANT SELECT ON c##CN04.PRODUCT             TO c##GIAMDOC4;
GRANT SELECT ON c##CN04.INVENTORY           TO c##GIAMDOC4;
GRANT SELECT ON c##CN04.SALE                TO c##GIAMDOC4;
GRANT SELECT ON c##CN04.PRODUCT             TO c##QUANLYKHO4;
GRANT SELECT ON c##CN04.INVENTORY           TO c##QUANLYKHO4;
GRANT SELECT ON c##CN04.PRODUCT             TO c##NHANVIEN4;
GRANT SELECT ON c##CN04.SALE                TO c##NHANVIEN4;

---------------------------------------------------------------

--CREATE PUBLIC DATABASE LINK CN01_DBLINK CONNECT TO c##CN01 IDENTIFIED BY GIAMDOC1 USING 'PHUONG';
--CREATE PUBLIC DATABASE LINK CN02_DBLINK CONNECT TO c##CN02 IDENTIFIED BY GIAMDOC2 USING 'TAN';
--CREATE PUBLIC DATABASE LINK CN03_DBLINK CONNECT TO c##CN03 IDENTIFIED BY GIAMDOC3 USING 'TRINH';