SET DEFINE OFF

CREATE TABLE PRODUCT ( 
PRODUCT_ID VARCHAR2(10)  PRIMARY KEY,
COLOR VARCHAR2(26),
GENDER VARCHAR2(128),
PRODUCT_GROUP VARCHAR2(128),
SIZE_PRODUCT NUMBER(38),
AGE_GROUP VARCHAR2(128),
ACTIVITY_GROUP VARCHAR2(26),
HEEL_HEIGHT VARCHAR2(128),
COST_PRICE2 NUMBER(38),
BRAND_NAME VARCHAR2(128),
VENDOR_NAME VARCHAR2(128));



INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP001DEN42', 'DEN', 'MEN', 'DEP', 42, '40 ??n <60 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 51000, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP002XAM39', 'XAM', 'MEN', 'DEP', 39, '24 ??n <40 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 59160, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP003TIM38', 'TIM', 'WOM', 'DEP', 38, '16 ??n <24 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 55760, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP004XAM35', 'XAM', 'WOM', 'DEP', 35, '16 ??n <24 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 55760, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP005XAM38', 'XAM', 'WOM', 'DEP', 38, '16 ??n <24 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 55760, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP006XAM39', 'XAM', 'WOM', 'DEP', 39, '16 ??n <24 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 55760, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP007DEN24', 'DEN', 'GIR', 'GIA', 24, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 132600, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP008TRG35', 'TRG', 'MEN', 'PKI', 35, 'Khác', 'Khác', 'KHÁC', 13600, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP009DEN28', 'DEN', 'BOY', 'SAN', 28, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 153000, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP010DEN40', 'DEN', 'MEN', 'DEP', 40, '24 ??n <40 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 136000, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP011DEN41', 'DEN', 'MEN', 'DEP', 41, '24 ??n <40 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 136000, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP012KEM39', 'KEM', 'MEN', 'DEP', 39, '40 ??n <60 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 89760, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP013HOG28', 'HOG', 'GIR', 'GIA', 28, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 149600, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP014HOG36', 'HOG', 'GIR', 'SAN', 36, '10 ??n <16 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 193800, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP015HOG37', 'HOG', 'GIR', 'SAN', 37, '10 ??n <16 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 193800, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP016TRG42', 'TRG', 'MEN', 'DEP', 42, '16 ??n <24 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 108800, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP017BAC32', 'BAC', 'GIR', 'GIA', 32, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 156400, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP018DEN31', 'DEN', 'BOY', 'SAN', 31, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 193800, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP019DEN33', 'DEN', 'BOY', 'SAN', 33, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 193800, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP020DEN36', 'DEN', 'BOY', 'SAN', 36, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 204000, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP021DEN38', 'DEN', 'BOY', 'SAN', 38, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 204000, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP022XAM28', 'XAM', 'BOY', 'SAN', 28, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 187000, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP023CAM39', 'CAM', 'MEN', 'DEP', 39, '24 ??n <40 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 136000, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP024CAM43', 'CAM', 'MEN', 'DEP', 43, '24 ??n <40 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 136000, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP025XMN39', 'XMN', 'MEN', 'DEP', 39, '24 ??n <40 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 136000, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP026XMN40', 'XMN', 'MEN', 'DEP', 40, '24 ??n <40 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 136000, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP027XMN42', 'XMN', 'MEN', 'DEP', 42, '24 ??n <40 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 136000, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP028HOG35', 'HOG', 'WOM', 'SAN', 35, '16 ??n <24 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 295800, 'Brand2', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP029DEN33', 'DEN', 'GIR', 'GIA', 33, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 200600, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP030DEN35', 'DEN', 'GIR', 'GIA', 35, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 214200, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP031HOG30', 'HOG', 'GIR', 'GIA', 30, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 200600, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP032TRG30', 'TRG', 'GIR', 'GIA', 30, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 204000, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP033DEN33', 'DEN', 'GIR', 'GIA', 33, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 210800, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP034DEN37', 'DEN', 'GIR', 'GIA', 37, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 224400, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP035HOG32', 'HOG', 'GIR', 'GIA', 32, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 210800, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP036DEN39', 'DEN', 'MEN', 'SAN', 39, '16 ??n <24 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 309400, 'Brand2', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP037DEN38', 'DEN', 'WOM', 'DEP', 38, '24 ??n <40 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 98600, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP038DEN32', 'DEN', 'GIR', 'GIA', 32, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 227800, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP039DEN36', 'DEN', 'GIR', 'GIA', 36, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 241400, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP040HOG36', 'HOG', 'GIR', 'GIA', 36, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 241400, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP041DEN39', 'DEN', 'WOM', 'GIA', 39, '24 ??n <40 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 5 phân', 309400, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP042HOL36', 'HOL', 'WOM', 'GIA', 36, '24 ??n <40 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 5 phân', 309400, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP043HOL38', 'HOL', 'WOM', 'GIA', 38, '24 ??n <40 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 5 phân', 309400, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP044HOL39', 'HOL', 'WOM', 'GIA', 39, '24 ??n <40 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 5 phân', 309400, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP045XAM30', 'XAM', 'BOY', 'SAN', 30, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 193800, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP046XAM37', 'XAM', 'BOY', 'SAN', 37, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 204000, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP047HOG34', 'HOG', 'GIR', 'SAN', 34, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 207400, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP048CAM40', 'CAM', 'MEN', 'SAN', 40, '16 ??n <24 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 316200, 'Brand2', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP049DEN28', 'DEN', 'BOY', 'DEP', 28, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 88400, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP050DEN34', 'DEN', 'BOY', 'DEP', 34, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 95200, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP051DEN37', 'DEN', 'BOY', 'DEP', 37, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 95200, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP052XDG29', 'XDG', 'BOY', 'DEP', 29, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 88400, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP053XDG33', 'XDG', 'BOY', 'DEP', 33, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 88400, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP054XDG26', 'XDG', 'BOY', 'DEP', 26, '3 ??n <6 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 93160, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP055XAM34', 'XAM', 'BOY', 'SAN', 34, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 214200, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP056HOG33', 'HOG', 'GIR', 'DEP', 33, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 88400, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP057HOG27', 'HOG', 'GIR', 'DEP', 27, '3 ??n <6 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 93160, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP058HOG32', 'HOG', 'GIR', 'DEP', 32, '3 ??n <6 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 96560, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP059XNH38', 'XNH', 'MEN', 'DEP', 38, '24 ??n <40 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 136000, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP060CAM33', 'CAM', 'BOY', 'SAN', 33, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 204750, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP061DEN32', 'DEN', 'BOY', 'SAN', 32, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 193800, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP062XNH34', 'XNH', 'BOY', 'SAN', 34, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 204000, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP063HOG26', 'HOG', 'GIR', 'SAN', 26, '3 ??n <6 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 207400, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP064HOG29', 'HOG', 'GIR', 'SAN', 29, '3 ??n <6 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 214200, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP065DEN40', 'DEN', 'MEN', 'DEP', 40, '24 ??n <40 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 89760, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP066DEN43', 'DEN', 'MEN', 'DEP', 43, '24 ??n <40 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 89760, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP067DEN28', 'DEN', 'BOY', 'SAN', 28, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 183600, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP068DOO32', 'DOO', 'BOY', 'SAN', 32, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 183600, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP069XAM37', 'XAM', 'BOY', 'SAN', 37, '10 ??n <16 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 200600, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP070XAM39', 'XAM', 'BOY', 'SAN', 39, '10 ??n <16 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 200600, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP071DOO37', 'DOO', 'BOY', 'DEP', 37, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 95200, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP072XAM32', 'XAM', 'BOY', 'SAN', 32, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 200600, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP073HOG28', 'HOG', 'GIR', 'SAN', 28, '3 ??n <6 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 204000, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP074XNH35', 'XNH', 'GIR', 'SAN', 35, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 207400, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP075HOL35', 'HOL', 'GIR', 'SAN', 35, '10 ??n <16 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 200600, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP076HOG25', 'HOG', 'GIR', 'DEP', 25, '3 ??n <6 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 102000, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP077DEN39', 'DEN', 'MEN', 'DEP', 39, '24 ??n <40 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 227800, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP078DEN40', 'DEN', 'MEN', 'DEP', 40, '40 ??n <60 tu?i', 'Th??ng nh?t/Tr??ng h?c', NULL, 63240, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP079DEN42', 'DEN', 'MEN', 'DEP', 42, '40 ??n <60 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 61200, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP080NAU40', 'NAU', 'MEN', 'DEP', 40, '40 ??n <60 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 61200, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP081XAM39', 'XAM', 'MEN', 'DEP', 39, '24 ??n <40 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 72080, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP082XAM41', 'XAM', 'MEN', 'SAN', 41, '24 ??n <40 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 316200, 'Brand2', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP083XAM39', 'XAM', 'WOM', 'DEP', 39, '16 ??n <24 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 68680, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP084XNH35', 'XNH', 'WOM', 'DEP', 35, '16 ??n <24 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 70720, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP085DEN35', 'DEN', 'BOY', 'DEP', 35, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 95200, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP086NAU42', 'NAU', 'MEN', 'DEP', 42, '40 ??n <60 tu?i', 'Th??ng nh?t/Tr??ng h?c', NULL, 63240, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP087DEN39', 'DEN', 'WOM', 'SAN', 39, '16 ??n <24 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 316200, 'Brand2', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP088DEN39', 'DEN', 'WOM', 'SAN', 39, '16 ??n <24 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 316200, 'Brand2', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP089DEN40', 'DEN', 'MEN', 'DEP', 40, '24 ??n <40 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 113560, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP090DOO41', 'DOO', 'MEN', 'DEP', 41, '16 ??n <24 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 59160, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP091DEN40', 'DEN', 'MEN', 'DEP', 40, '24 ??n <40 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 54400, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP092DEN38', 'DEN', 'MEN', 'DEP', 38, '16 ??n <24 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 54400, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP093DEN40', 'DEN', 'MEN', 'GIA', 40, '40 ??n <60 tu?i', 'V?n phòng', '?? S?p', 550800, 'Brand1', 'vendor10');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP094DEN42', 'DEN', 'MEN', 'GIA', 42, '40 ??n <60 tu?i', 'V?n phòng', '?? S?p', 571200, 'Brand1', 'vendor11');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP095DEN39', 'DEN', 'MEN', 'GIA', 39, '40 ??n <60 tu?i', 'V?n phòng', '?? S?p', 571200, 'Brand1', 'vendor11');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP096DEN40', 'DEN', 'MEN', 'GIA', 40, '40 ??n <60 tu?i', 'V?n phòng', '?? S?p', 435200, 'Brand1', 'vendor11');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP097NAD43', 'NAD', 'MEN', 'GIA', 43, '40 ??n <60 tu?i', 'V?n phòng', '?? S?p', 435200, 'Brand1', 'vendor11');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP098DOO30', 'DOO', 'BOY', 'DEP', 30, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 3 phân', 122400, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP099DEN37', 'DEN', 'BOY', 'SAN', 37, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 197200, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP100DEN41', 'DEN', 'MEN', 'SAN', 41, '24 ??n <40 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 248200, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP101DEN37', 'DEN', 'WOM', 'SAN', 37, '24 ??n <40 tu?i', 'Th??ng nh?t/Tr??ng h?c', 'Cao 5 phân', 237320, 'Brand1', 'vendor0');

INSERT INTO PRODUCT (PRODUCT_ID, COLOR, GENDER, PRODUCT_GROUP, SIZE_PRODUCT, AGE_GROUP, ACTIVITY_GROUP, HEEL_HEIGHT, COST_PRICE2, BRAND_NAME, VENDOR_NAME) 
VALUES ('SP102DOO36', 'DOO', 'BOY', 'SAN', 36, '6 ??n <10 tu?i', 'Th??ng nh?t/Tr??ng h?c', '?? S?p', 200600, 'Brand1', 'vendor0');

