SET DEFINE OFF

CREATE TABLE DistributionChannel ( 
    SITE_STORE NUMBER(4) PRIMARY KEY,
    CHANNEL_ID VARCHAR2(4),
    REGION VARCHAR2(26),
    CITY_LEVEL VARCHAR2(26),
    STORE_CONCEPT VARCHAR2(26),
    TRADE_TERM VARCHAR2(26),
    AREA_RANGE VARCHAR2(26),
    STORE_TYPE VARCHAR2(26),
    URBANIZATION VARCHAR2(26),
    BRANCH_AREA VARCHAR2(26),
    ADDRESS_2 VARCHAR2(26),
    ADDRESS_3 VARCHAR2(26)
    );



INSERT INTO DistributionChannel (SITE_STORE, CHANNEL_ID, REGION, CITY_LEVEL, STORE_CONCEPT, TRADE_TERM, AREA_RANGE, STORE_TYPE, URBANIZATION, BRANCH_AREA, ADDRESS_2, ADDRESS_3) 
VALUES (1201, 'CHTT', 'KVMB', 'C?p TW', 'C?a hàng B thông th??ng', 'Drop-ship', '100 m2 < và <= 150 m2', '??c l?p', 'N?i thành', 'CNMB', 'Q. ??ng ?a', 'HNI');

INSERT INTO DistributionChannel (SITE_STORE, CHANNEL_ID, REGION, CITY_LEVEL, STORE_CONCEPT, TRADE_TERM, AREA_RANGE, STORE_TYPE, URBANIZATION, BRANCH_AREA, ADDRESS_2, ADDRESS_3) 
VALUES (1202, 'CHTT', 'KVMB', 'C?p 1', 'C?a hàng B thông th??ng', 'Drop-ship', '50 m2 < và <= 100 m2', '??c l?p', 'N?i thành', 'CNMB', 'Q. Lê Chân', 'HPG');

INSERT INTO DistributionChannel (SITE_STORE, CHANNEL_ID, REGION, CITY_LEVEL, STORE_CONCEPT, TRADE_TERM, AREA_RANGE, STORE_TYPE, URBANIZATION, BRANCH_AREA, ADDRESS_2, ADDRESS_3) 
VALUES (1203, 'CHTT', 'KVMB', 'C?p TW', 'C?a hàng B thông th??ng', 'Drop-ship', '50 m2 < và <= 100 m2', '??c l?p', 'N?i thành', 'CNMB', 'Q. C?u Gi?y', 'HNI');

INSERT INTO DistributionChannel (SITE_STORE, CHANNEL_ID, REGION, CITY_LEVEL, STORE_CONCEPT, TRADE_TERM, AREA_RANGE, STORE_TYPE, URBANIZATION, BRANCH_AREA, ADDRESS_2, ADDRESS_3) 
VALUES (1204, 'CHTT', 'KVMB', 'C?p 1', 'C?a hàng B thông th??ng', 'Drop-ship', '50 m2 < và <= 100 m2', '??c l?p', 'N?i thành', 'CNMB', 'Q. Lê Chân', 'HPG');

